/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.annotation.validation;

import de.uniba.wiai.seda.fha.annotation.validation.AbstractAnnotationValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AnnotationValidator extends AbstractAnnotationValidator {
}
