/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class AwsQuickfixProvider extends DefaultQuickfixProvider {
}
