/*
* generated by Xtext
*/
package de.uniba.wiai.seda.fha.som.aws.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.uniba.wiai.seda.fha.som.aws.services.AwsGrammarAccess;

public class AwsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AwsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.uniba.wiai.seda.fha.som.aws.parser.antlr.internal.InternalAwsParser createParser(XtextTokenStream stream) {
		return new de.uniba.wiai.seda.fha.som.aws.parser.antlr.internal.InternalAwsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AwS";
	}
	
	public AwsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AwsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
