/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.soa.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.uniba.wiai.seda.fha.som.aws.soa.ui.internal.SoaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SoaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SoaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SoaActivator.getInstance().getInjector(SoaActivator.DE_UNIBA_WIAI_SEDA_FHA_SOM_AWS_SOA_SOA);
	}
	
}
