/*
* generated by Xtext
*/
package de.uniba.wiai.seda.somsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SomSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/uniba/wiai/seda/somsl/parser/antlr/internal/InternalSomSL.tokens");
	}
}
