<?xml version="1.0" encoding="UTF-8"?>
<serviceModel:ServiceModell xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:serviceModel="http://www.uniba.de/wiai/seda/servicemodel/ServiceModel" name="ecar" version="0.2">
  <services xsi:type="serviceModel:Entityservice" name="Kundenservice">
    <entities name="Kunde"/>
    <entities name="Fahrer"/>
  </services>
  <services xsi:type="serviceModel:Vorgangsservice" name="Verkehrsamt">
    <services name=">Buchung3"/>
  </services>
  <services xsi:type="serviceModel:Vorgangsservice" name="Rezeption">
    <services name=">Buchung2"/>
    <services name=">Buchung"/>
  </services>
</serviceModel:ServiceModell>
