/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.somslmarked.validation;

import de.uniba.wiai.seda.somslmarked.validation.AbstractSomSLMarkedValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SomSLMarkedValidator extends AbstractSomSLMarkedValidator {
}
