/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.somsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSomSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.uniba.wiai.seda.somsl.somSL.SomSLPackage.eINSTANCE);
		return result;
	}
}
