/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.ui.contentassist;

import de.uniba.wiai.seda.fha.som.aws.ui.contentassist.AbstractAwsProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AwsProposalProvider extends AbstractAwsProposalProvider {
}
