/*
* generated by Xtext
*/
package de.uniba.wiai.seda.somsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SomSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.uniba.wiai.seda.somsl.ui.internal.SomSLActivator.getInstance().getInjector("de.uniba.wiai.seda.somsl.SomSL");
	}
	
}
