/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.somsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SomSLUiModule extends de.uniba.wiai.seda.somsl.ui.AbstractSomSLUiModule {
	public SomSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
