/*
* generated by Xtext
*/
package de.uniba.wiai.seda.fha.swarchitektur;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SwarchitekturUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.uniba.wiai.seda.fha.swarchitektur.ui.internal.SwarchitekturActivator.getInstance().getInjector("de.uniba.wiai.seda.fha.swarchitektur.Swarchitektur");
	}
	
}
