/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AwsUiModule extends de.uniba.wiai.seda.fha.som.aws.ui.AbstractAwsUiModule {
	public AwsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
