/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.swarchitektur.validation;

import de.uniba.wiai.seda.fha.swarchitektur.validation.AbstractSwarchitekturValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SwarchitekturValidator extends AbstractSwarchitekturValidator {
}
