/*
* generated by Xtext
*/
package de.uniba.wiai.seda.somslmarked.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.uniba.wiai.seda.somslmarked.services.SomSLMarkedGrammarAccess;

public class SomSLMarkedParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SomSLMarkedGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.uniba.wiai.seda.somslmarked.parser.antlr.internal.InternalSomSLMarkedParser createParser(XtextTokenStream stream) {
		return new de.uniba.wiai.seda.somslmarked.parser.antlr.internal.InternalSomSLMarkedParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AwS";
	}
	
	public SomSLMarkedGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SomSLMarkedGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
