/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.soa;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SoaRuntimeModule extends de.uniba.wiai.seda.fha.som.aws.soa.AbstractSoaRuntimeModule {

}
