/*
* generated by Xtext
*/
package de.uniba.wiai.seda.somslmarked;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SomSLMarkedUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.uniba.wiai.seda.somslmarked.ui.internal.SomSLMarkedActivator.getInstance().getInjector("de.uniba.wiai.seda.somslmarked.SomSLMarked");
	}
	
}
