/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.swarchitektur.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SwarchitekturUiModule extends de.uniba.wiai.seda.fha.swarchitektur.ui.AbstractSwarchitekturUiModule {
	public SwarchitekturUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
