/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.soa.validation;

import de.uniba.wiai.seda.fha.som.aws.soa.validation.AbstractSoaValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SoaValidator extends AbstractSoaValidator {
}
