/*
* generated by Xtext
*/
package de.uniba.wiai.seda.fha.swarchitektur.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SwarchitekturAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/uniba/wiai/seda/fha/swarchitektur/parser/antlr/internal/InternalSwarchitektur.tokens");
	}
}
