/*
* generated by Xtext
*/
package de.uniba.wiai.seda.fha.swarchitektur.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.uniba.wiai.seda.fha.swarchitektur.services.SwarchitekturGrammarAccess;

public class SwarchitekturParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SwarchitekturGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.uniba.wiai.seda.fha.swarchitektur.parser.antlr.internal.InternalSwarchitekturParser createParser(XtextTokenStream stream) {
		return new de.uniba.wiai.seda.fha.swarchitektur.parser.antlr.internal.InternalSwarchitekturParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Architektur";
	}
	
	public SwarchitekturGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SwarchitekturGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
