/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.somsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SomSLRuntimeModule extends de.uniba.wiai.seda.somsl.AbstractSomSLRuntimeModule {

}
