/*
* generated by Xtext
*/
package de.uniba.wiai.seda.somsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SomSLStandaloneSetup extends SomSLStandaloneSetupGenerated{

	public static void doSetup() {
		new SomSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

