/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.soa.ui.contentassist

import de.uniba.wiai.seda.fha.som.aws.soa.ui.contentassist.AbstractSoaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SoaProposalProvider extends AbstractSoaProposalProvider {
}
