/*
* generated by Xtext
*/
package de.uniba.wiai.seda.fha.swarchitektur;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SwarchitekturStandaloneSetup extends SwarchitekturStandaloneSetupGenerated{

	public static void doSetup() {
		new SwarchitekturStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

