/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.swarchitektur;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SwarchitekturRuntimeModule extends de.uniba.wiai.seda.fha.swarchitektur.AbstractSwarchitekturRuntimeModule {

}
