/*
* generated by Xtext
*/
package de.uniba.wiai.seda.fha.annotation.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.uniba.wiai.seda.fha.annotation.services.AnnotationGrammarAccess;

public class AnnotationParser extends AbstractContentAssistParser {
	
	@Inject
	private AnnotationGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.uniba.wiai.seda.fha.annotation.ui.contentassist.antlr.internal.InternalAnnotationParser createParser() {
		de.uniba.wiai.seda.fha.annotation.ui.contentassist.antlr.internal.InternalAnnotationParser result = new de.uniba.wiai.seda.fha.annotation.ui.contentassist.antlr.internal.InternalAnnotationParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAnnotationAccess().getAlternatives(), "rule__Annotation__Alternatives");
					put(grammarAccess.getNameAccess().getGroup(), "rule__Name__Group__0");
					put(grammarAccess.getMergeAccess().getGroup(), "rule__Merge__Group__0");
					put(grammarAccess.getIgnoreAccess().getGroup(), "rule__Ignore__Group__0");
					put(grammarAccess.getVersionAccess().getGroup(), "rule__Version__Group__0");
					put(grammarAccess.getNameAccess().getNameAssignment_1(), "rule__Name__NameAssignment_1");
					put(grammarAccess.getMergeAccess().getNameAssignment_1(), "rule__Merge__NameAssignment_1");
					put(grammarAccess.getVersionAccess().getVersionAssignment_1(), "rule__Version__VersionAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.uniba.wiai.seda.fha.annotation.ui.contentassist.antlr.internal.InternalAnnotationParser typedParser = (de.uniba.wiai.seda.fha.annotation.ui.contentassist.antlr.internal.InternalAnnotationParser) parser;
			typedParser.entryRuleAnnotation();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AnnotationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AnnotationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
