/*
* generated by Xtext
*/
package de.uniba.wiai.seda.fha.som.aws.soa.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.uniba.wiai.seda.fha.som.aws.soa.services.SoaGrammarAccess;

public class SoaParser extends AbstractContentAssistParser {
	
	@Inject
	private SoaGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.uniba.wiai.seda.fha.som.aws.soa.ui.contentassist.antlr.internal.InternalSoaParser createParser() {
		de.uniba.wiai.seda.fha.som.aws.soa.ui.contentassist.antlr.internal.InternalSoaParser result = new de.uniba.wiai.seda.fha.som.aws.soa.ui.contentassist.antlr.internal.InternalSoaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSOA_AwSAccess().getAlternatives_4(), "rule__SOA_AwS__Alternatives_4");
					put(grammarAccess.getServiceAccess().getAlternatives(), "rule__Service__Alternatives");
					put(grammarAccess.getWorkflowAccess().getAlternatives_2(), "rule__Workflow__Alternatives_2");
					put(grammarAccess.getSchemaAccess().getAlternatives(), "rule__Schema__Alternatives");
					put(grammarAccess.getVOSAccess().getAlternatives_0(), "rule__VOS__Alternatives_0");
					put(grammarAccess.getVOSAccess().getAlternatives_2(), "rule__VOS__Alternatives_2");
					put(grammarAccess.getKOSAccess().getAlternatives_0(), "rule__KOS__Alternatives_0");
					put(grammarAccess.getKOSAccess().getAlternatives_2(), "rule__KOS__Alternatives_2");
					put(grammarAccess.getObjekttypAccess().getAlternatives(), "rule__Objekttyp__Alternatives");
					put(grammarAccess.getVOTAccess().getAlternatives_4(), "rule__VOT__Alternatives_4");
					put(grammarAccess.getKOTAccess().getAlternatives(), "rule__KOT__Alternatives");
					put(grammarAccess.getOOTAccess().getAlternatives_4(), "rule__OOT__Alternatives_4");
					put(grammarAccess.getLOTAccess().getAlternatives_4(), "rule__LOT__Alternatives_4");
					put(grammarAccess.getTOTAccess().getAlternatives_4(), "rule__TOT__Alternatives_4");
					put(grammarAccess.getBeziehungAccess().getAlternatives(), "rule__Beziehung__Alternatives");
					put(grammarAccess.getInteracts_withAccess().getKardinalitaetAlternatives_3_0(), "rule__Interacts_with__KardinalitaetAlternatives_3_0");
					put(grammarAccess.getIs_aAccess().getKardinalitaetAlternatives_3_0(), "rule__Is_a__KardinalitaetAlternatives_3_0");
					put(grammarAccess.getIs_part_ofAccess().getKardinalitaetAlternatives_3_0(), "rule__Is_part_of__KardinalitaetAlternatives_3_0");
					put(grammarAccess.getKardinalitaetAccess().getAlternatives(), "rule__Kardinalitaet__Alternatives");
					put(grammarAccess.getKardinalitaet01Access().getAlternatives_0(), "rule__Kardinalitaet01__Alternatives_0");
					put(grammarAccess.getKardinalitaet0xAccess().getAlternatives_0(), "rule__Kardinalitaet0x__Alternatives_0");
					put(grammarAccess.getKardinalitaet11Access().getAlternatives_0(), "rule__Kardinalitaet11__Alternatives_0");
					put(grammarAccess.getKardinalitaet1xAccess().getAlternatives_0(), "rule__Kardinalitaet1x__Alternatives_0");
					put(grammarAccess.getAnnotationAccess().getAlternatives(), "rule__Annotation__Alternatives");
					put(grammarAccess.getSOA_AwSAccess().getGroup(), "rule__SOA_AwS__Group__0");
					put(grammarAccess.getSOA_AwSAccess().getGroup_2(), "rule__SOA_AwS__Group_2__0");
					put(grammarAccess.getVorgangsserviceAccess().getGroup(), "rule__Vorgangsservice__Group__0");
					put(grammarAccess.getVorgangsserviceElementarAccess().getGroup(), "rule__VorgangsserviceElementar__Group__0");
					put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
					put(grammarAccess.getServiceMethodeAccess().getGroup(), "rule__ServiceMethode__Group__0");
					put(grammarAccess.getWorkflowAccess().getGroup(), "rule__Workflow__Group__0");
					put(grammarAccess.getOrchestrierungAccess().getGroup(), "rule__Orchestrierung__Group__0");
					put(grammarAccess.getOrchestrierungAccess().getGroup_0(), "rule__Orchestrierung__Group_0__0");
					put(grammarAccess.getChoreographieLokalAccess().getGroup(), "rule__ChoreographieLokal__Group__0");
					put(grammarAccess.getChoreographieLokalAccess().getGroup_0(), "rule__ChoreographieLokal__Group_0__0");
					put(grammarAccess.getEntityserviceAccess().getGroup(), "rule__Entityservice__Group__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getAwSAccess().getGroup(), "rule__AwS__Group__0");
					put(grammarAccess.getAwSAccess().getGroup_2(), "rule__AwS__Group_2__0");
					put(grammarAccess.getVOSAccess().getGroup(), "rule__VOS__Group__0");
					put(grammarAccess.getKOSAccess().getGroup(), "rule__KOS__Group__0");
					put(grammarAccess.getVOTAccess().getGroup(), "rule__VOT__Group__0");
					put(grammarAccess.getOOTAccess().getGroup(), "rule__OOT__Group__0");
					put(grammarAccess.getLOTAccess().getGroup(), "rule__LOT__Group__0");
					put(grammarAccess.getTOTAccess().getGroup(), "rule__TOT__Group__0");
					put(grammarAccess.getAttributAccess().getGroup(), "rule__Attribut__Group__0");
					put(grammarAccess.getOperatorAccess().getGroup(), "rule__Operator__Group__0");
					put(grammarAccess.getInteracts_withAccess().getGroup(), "rule__Interacts_with__Group__0");
					put(grammarAccess.getIs_aAccess().getGroup(), "rule__Is_a__Group__0");
					put(grammarAccess.getIs_part_ofAccess().getGroup(), "rule__Is_part_of__Group__0");
					put(grammarAccess.getKardinalitaet01Access().getGroup(), "rule__Kardinalitaet01__Group__0");
					put(grammarAccess.getKardinalitaet0xAccess().getGroup(), "rule__Kardinalitaet0x__Group__0");
					put(grammarAccess.getKardinalitaet11Access().getGroup(), "rule__Kardinalitaet11__Group__0");
					put(grammarAccess.getKardinalitaet1xAccess().getGroup(), "rule__Kardinalitaet1x__Group__0");
					put(grammarAccess.getNameAccess().getGroup(), "rule__Name__Group__0");
					put(grammarAccess.getMergeAccess().getGroup(), "rule__Merge__Group__0");
					put(grammarAccess.getIgnoreAccess().getGroup(), "rule__Ignore__Group__0");
					put(grammarAccess.getVersionAccess().getGroup(), "rule__Version__Group__0");
					put(grammarAccess.getSOA_AwSAccess().getNameAssignment_1(), "rule__SOA_AwS__NameAssignment_1");
					put(grammarAccess.getSOA_AwSAccess().getVersionAssignment_2_1(), "rule__SOA_AwS__VersionAssignment_2_1");
					put(grammarAccess.getSOA_AwSAccess().getVosAssignment_3_0(), "rule__SOA_AwS__VosAssignment_3_0");
					put(grammarAccess.getSOA_AwSAccess().getKosAssignment_3_1(), "rule__SOA_AwS__KosAssignment_3_1");
					put(grammarAccess.getSOA_AwSAccess().getVorgangsservicesAssignment_4_0(), "rule__SOA_AwS__VorgangsservicesAssignment_4_0");
					put(grammarAccess.getSOA_AwSAccess().getEntityservicesAssignment_4_1(), "rule__SOA_AwS__EntityservicesAssignment_4_1");
					put(grammarAccess.getVorgangsserviceAccess().getNameAssignment_1(), "rule__Vorgangsservice__NameAssignment_1");
					put(grammarAccess.getVorgangsserviceAccess().getChoreographieIFAssignment_3(), "rule__Vorgangsservice__ChoreographieIFAssignment_3");
					put(grammarAccess.getVorgangsserviceAccess().getVorgangsservicesElementarAssignment_4(), "rule__Vorgangsservice__VorgangsservicesElementarAssignment_4");
					put(grammarAccess.getVorgangsserviceAccess().getWorkflowAssignment_5(), "rule__Vorgangsservice__WorkflowAssignment_5");
					put(grammarAccess.getVorgangsserviceElementarAccess().getNameAssignment_0(), "rule__VorgangsserviceElementar__NameAssignment_0");
					put(grammarAccess.getVorgangsserviceElementarAccess().getKomponentenObjekttypAssignment_2(), "rule__VorgangsserviceElementar__KomponentenObjekttypAssignment_2");
					put(grammarAccess.getVorgangsserviceElementarAccess().getInterfaceAssignment_3(), "rule__VorgangsserviceElementar__InterfaceAssignment_3");
					put(grammarAccess.getInterfaceAccess().getNameAssignment_0(), "rule__Interface__NameAssignment_0");
					put(grammarAccess.getInterfaceAccess().getMethodenAssignment_2(), "rule__Interface__MethodenAssignment_2");
					put(grammarAccess.getServiceMethodeAccess().getNameAssignment_0(), "rule__ServiceMethode__NameAssignment_0");
					put(grammarAccess.getServiceMethodeAccess().getParameterAssignment_2(), "rule__ServiceMethode__ParameterAssignment_2");
					put(grammarAccess.getWorkflowAccess().getOrchestrierungAssignment_2_0(), "rule__Workflow__OrchestrierungAssignment_2_0");
					put(grammarAccess.getWorkflowAccess().getChoreographieAssignment_2_1(), "rule__Workflow__ChoreographieAssignment_2_1");
					put(grammarAccess.getOrchestrierungAccess().getBedingungAssignment_0_1(), "rule__Orchestrierung__BedingungAssignment_0_1");
					put(grammarAccess.getOrchestrierungAccess().getMethode1Assignment_1(), "rule__Orchestrierung__Methode1Assignment_1");
					put(grammarAccess.getOrchestrierungAccess().getMethode2Assignment_3(), "rule__Orchestrierung__Methode2Assignment_3");
					put(grammarAccess.getChoreographieLokalAccess().getBedingungAssignment_0_1(), "rule__ChoreographieLokal__BedingungAssignment_0_1");
					put(grammarAccess.getChoreographieLokalAccess().getMethode1Assignment_1(), "rule__ChoreographieLokal__Methode1Assignment_1");
					put(grammarAccess.getChoreographieLokalAccess().getService2Assignment_3(), "rule__ChoreographieLokal__Service2Assignment_3");
					put(grammarAccess.getChoreographieLokalAccess().getMethode2Assignment_5(), "rule__ChoreographieLokal__Methode2Assignment_5");
					put(grammarAccess.getBedingungAccess().getBedingungAssignment(), "rule__Bedingung__BedingungAssignment");
					put(grammarAccess.getEntityserviceAccess().getNameAssignment_1(), "rule__Entityservice__NameAssignment_1");
					put(grammarAccess.getEntityserviceAccess().getInterfaceAssignment_3(), "rule__Entityservice__InterfaceAssignment_3");
					put(grammarAccess.getEntityserviceAccess().getEntitiesAssignment_4(), "rule__Entityservice__EntitiesAssignment_4");
					put(grammarAccess.getEntityAccess().getNameAssignment_0(), "rule__Entity__NameAssignment_0");
					put(grammarAccess.getEntityAccess().getKomponentenObjekttypAssignment_2(), "rule__Entity__KomponentenObjekttypAssignment_2");
					put(grammarAccess.getEntityAccess().getInterfaceAssignment_3(), "rule__Entity__InterfaceAssignment_3");
					put(grammarAccess.getAwSAccess().getNameAssignment_1(), "rule__AwS__NameAssignment_1");
					put(grammarAccess.getAwSAccess().getVersionAssignment_2_1(), "rule__AwS__VersionAssignment_2_1");
					put(grammarAccess.getAwSAccess().getKosAssignment_3_0(), "rule__AwS__KosAssignment_3_0");
					put(grammarAccess.getAwSAccess().getVosAssignment_3_1(), "rule__AwS__VosAssignment_3_1");
					put(grammarAccess.getVOSAccess().getNameAssignment_0_0(), "rule__VOS__NameAssignment_0_0");
					put(grammarAccess.getVOSAccess().getNameAssignment_0_1(), "rule__VOS__NameAssignment_0_1");
					put(grammarAccess.getVOSAccess().getObjekttypenAssignment_2_0(), "rule__VOS__ObjekttypenAssignment_2_0");
					put(grammarAccess.getVOSAccess().getBeziehungenAssignment_2_1(), "rule__VOS__BeziehungenAssignment_2_1");
					put(grammarAccess.getVOSAccess().getGliederungAssignment_2_2(), "rule__VOS__GliederungAssignment_2_2");
					put(grammarAccess.getKOSAccess().getNameAssignment_0_0(), "rule__KOS__NameAssignment_0_0");
					put(grammarAccess.getKOSAccess().getNameAssignment_0_1(), "rule__KOS__NameAssignment_0_1");
					put(grammarAccess.getKOSAccess().getObjekttypenAssignment_2_0(), "rule__KOS__ObjekttypenAssignment_2_0");
					put(grammarAccess.getKOSAccess().getBeziehungenAssignment_2_1(), "rule__KOS__BeziehungenAssignment_2_1");
					put(grammarAccess.getKOSAccess().getGliederungAssignment_2_2(), "rule__KOS__GliederungAssignment_2_2");
					put(grammarAccess.getVOTAccess().getAnnotationAssignment_0(), "rule__VOT__AnnotationAssignment_0");
					put(grammarAccess.getVOTAccess().getNameAssignment_2(), "rule__VOT__NameAssignment_2");
					put(grammarAccess.getVOTAccess().getAttributeAssignment_4_0(), "rule__VOT__AttributeAssignment_4_0");
					put(grammarAccess.getVOTAccess().getOperatorenAssignment_4_1(), "rule__VOT__OperatorenAssignment_4_1");
					put(grammarAccess.getOOTAccess().getAnnotationAssignment_0(), "rule__OOT__AnnotationAssignment_0");
					put(grammarAccess.getOOTAccess().getNameAssignment_2(), "rule__OOT__NameAssignment_2");
					put(grammarAccess.getOOTAccess().getAttributeAssignment_4_0(), "rule__OOT__AttributeAssignment_4_0");
					put(grammarAccess.getOOTAccess().getOperatorenAssignment_4_1(), "rule__OOT__OperatorenAssignment_4_1");
					put(grammarAccess.getLOTAccess().getAnnotationAssignment_0(), "rule__LOT__AnnotationAssignment_0");
					put(grammarAccess.getLOTAccess().getNameAssignment_2(), "rule__LOT__NameAssignment_2");
					put(grammarAccess.getLOTAccess().getAttributeAssignment_4_0(), "rule__LOT__AttributeAssignment_4_0");
					put(grammarAccess.getLOTAccess().getOperatorenAssignment_4_1(), "rule__LOT__OperatorenAssignment_4_1");
					put(grammarAccess.getTOTAccess().getAnnotationAssignment_0(), "rule__TOT__AnnotationAssignment_0");
					put(grammarAccess.getTOTAccess().getNameAssignment_2(), "rule__TOT__NameAssignment_2");
					put(grammarAccess.getTOTAccess().getAttributeAssignment_4_0(), "rule__TOT__AttributeAssignment_4_0");
					put(grammarAccess.getTOTAccess().getOperatorenAssignment_4_1(), "rule__TOT__OperatorenAssignment_4_1");
					put(grammarAccess.getAttributAccess().getTypAssignment_0(), "rule__Attribut__TypAssignment_0");
					put(grammarAccess.getAttributAccess().getNameAssignment_1(), "rule__Attribut__NameAssignment_1");
					put(grammarAccess.getOperatorAccess().getNameAssignment_0(), "rule__Operator__NameAssignment_0");
					put(grammarAccess.getOperatorAccess().getParameterAssignment_2(), "rule__Operator__ParameterAssignment_2");
					put(grammarAccess.getInteracts_withAccess().getAnnotationAssignment_0(), "rule__Interacts_with__AnnotationAssignment_0");
					put(grammarAccess.getInteracts_withAccess().getObjekttyp1Assignment_2(), "rule__Interacts_with__Objekttyp1Assignment_2");
					put(grammarAccess.getInteracts_withAccess().getKardinalitaetAssignment_3(), "rule__Interacts_with__KardinalitaetAssignment_3");
					put(grammarAccess.getInteracts_withAccess().getObjekttyp2Assignment_4(), "rule__Interacts_with__Objekttyp2Assignment_4");
					put(grammarAccess.getIs_aAccess().getAnnotationAssignment_0(), "rule__Is_a__AnnotationAssignment_0");
					put(grammarAccess.getIs_aAccess().getObjekttyp1Assignment_2(), "rule__Is_a__Objekttyp1Assignment_2");
					put(grammarAccess.getIs_aAccess().getKardinalitaetAssignment_3(), "rule__Is_a__KardinalitaetAssignment_3");
					put(grammarAccess.getIs_aAccess().getObjekttyp2Assignment_4(), "rule__Is_a__Objekttyp2Assignment_4");
					put(grammarAccess.getIs_part_ofAccess().getAnnotationAssignment_0(), "rule__Is_part_of__AnnotationAssignment_0");
					put(grammarAccess.getIs_part_ofAccess().getObjekttyp1Assignment_2(), "rule__Is_part_of__Objekttyp1Assignment_2");
					put(grammarAccess.getIs_part_ofAccess().getKardinalitaetAssignment_3(), "rule__Is_part_of__KardinalitaetAssignment_3");
					put(grammarAccess.getIs_part_ofAccess().getObjekttyp2Assignment_4(), "rule__Is_part_of__Objekttyp2Assignment_4");
					put(grammarAccess.getNameAccess().getNameAssignment_1(), "rule__Name__NameAssignment_1");
					put(grammarAccess.getMergeAccess().getNameAssignment_1(), "rule__Merge__NameAssignment_1");
					put(grammarAccess.getVersionAccess().getVersionAssignment_1(), "rule__Version__VersionAssignment_1");
					put(grammarAccess.getSOA_AwSAccess().getUnorderedGroup_3(), "rule__SOA_AwS__UnorderedGroup_3");
					put(grammarAccess.getAwSAccess().getUnorderedGroup_3(), "rule__AwS__UnorderedGroup_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.uniba.wiai.seda.fha.som.aws.soa.ui.contentassist.antlr.internal.InternalSoaParser typedParser = (de.uniba.wiai.seda.fha.som.aws.soa.ui.contentassist.antlr.internal.InternalSoaParser) parser;
			typedParser.entryRuleSOA_AwS();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SoaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SoaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
