/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.soa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SoaUiModule extends de.uniba.wiai.seda.fha.som.aws.soa.ui.AbstractSoaUiModule {
	public SoaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
