<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aws" nsURI="http://www.uniba.de/wiai/seda/fha/som/aws/Aws" nsPrefix="aws">
  <eClassifiers xsi:type="ecore:EClass" name="Aws">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objekttypen" upperBound="-1"
        eType="#//Objekttyp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beziehungen" upperBound="-1"
        eType="#//Beziehung" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objekttyp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribut" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operatoren" upperBound="-1"
        eType="#//Operator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KOT" eSuperTypes="#//Objekttyp"/>
  <eClassifiers xsi:type="ecore:EClass" name="OOT" eSuperTypes="#//KOT"/>
  <eClassifiers xsi:type="ecore:EClass" name="TOT" eSuperTypes="#//KOT"/>
  <eClassifiers xsi:type="ecore:EClass" name="LOT" eSuperTypes="#//KOT"/>
  <eClassifiers xsi:type="ecore:EClass" name="VOT" eSuperTypes="#//Objekttyp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outParam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inParam" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Beziehung">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objekttyp1" eType="#//Objekttyp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kardinalitaet" eType="#//Kardinalitaet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objekttyp2" eType="#//Objekttyp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interacts_with" eSuperTypes="#//Beziehung"/>
  <eClassifiers xsi:type="ecore:EClass" name="Is_a" eSuperTypes="#//Beziehung"/>
  <eClassifiers xsi:type="ecore:EClass" name="Is_part_of" eSuperTypes="#//Beziehung"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kardinalitaet"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kardinalitaet01" eSuperTypes="#//Kardinalitaet"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kardinalitaet0x" eSuperTypes="#//Kardinalitaet"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kardinalitaet11" eSuperTypes="#//Kardinalitaet"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kardinalitaet1x" eSuperTypes="#//Kardinalitaet"/>
</ecore:EPackage>
