/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.uniba.wiai.seda.fha.som.aws.ui.internal.AwsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AwsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AwsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AwsActivator.getInstance().getInjector(AwsActivator.DE_UNIBA_WIAI_SEDA_FHA_SOM_AWS_AWS);
	}
	
}
