/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.somslmarked.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSomSLMarkedValidator extends de.uniba.wiai.seda.somsl.annotation.validation.AnnotationValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.uniba.wiai.seda.somslmarked.somSLMarked.SomSLMarkedPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.uniba.de/wiai/seda/somsl/annotation/Annotation"));
		return result;
	}
}
