/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class AwsDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
