/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.somslmarked.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SomSLMarkedUiModule extends de.uniba.wiai.seda.somslmarked.ui.AbstractSomSLMarkedUiModule {
	public SomSLMarkedUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
