/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.annotation.ui.contentassist;

import de.uniba.wiai.seda.fha.annotation.ui.contentassist.AbstractAnnotationProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AnnotationProposalProvider extends AbstractAnnotationProposalProvider {
}
