/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.annotation;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AnnotationRuntimeModule extends de.uniba.wiai.seda.fha.annotation.AbstractAnnotationRuntimeModule {

}
