/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.fha.som.aws;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AwsRuntimeModule extends de.uniba.wiai.seda.fha.som.aws.AbstractAwsRuntimeModule {

}
