/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.somslmarked.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.uniba.wiai.seda.somslmarked.ui.internal.SomSLMarkedActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SomSLMarkedExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SomSLMarkedActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SomSLMarkedActivator.getInstance().getInjector(SomSLMarkedActivator.DE_UNIBA_WIAI_SEDA_SOMSLMARKED_SOMSLMARKED);
	}
	
}
