/*
* generated by Xtext
*/
package de.uniba.wiai.seda.fha.som.aws;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AwsStandaloneSetup extends AwsStandaloneSetupGenerated{

	public static void doSetup() {
		new AwsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

