/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.somslmarked.formatting;

import com.google.inject.Inject;
import de.uniba.wiai.seda.somslmarked.services.SomSLMarkedGrammarAccess;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.formatting.impl.FormattingConfig.LinewrapLocator;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
@SuppressWarnings("all")
public class SomSLMarkedFormatter extends AbstractDeclarativeFormatter {
  @Inject
  @Extension
  private SomSLMarkedGrammarAccess _somSLMarkedGrammarAccess;
  
  protected void configureFormatting(final FormattingConfig c) {
    LinewrapLocator _setLinewrap = c.setLinewrap(1, 1, 2);
    TerminalRule _sL_COMMENTRule = this._somSLMarkedGrammarAccess.getSL_COMMENTRule();
    _setLinewrap.before(_sL_COMMENTRule);
    LinewrapLocator _setLinewrap_1 = c.setLinewrap(1, 1, 2);
    TerminalRule _mL_COMMENTRule = this._somSLMarkedGrammarAccess.getML_COMMENTRule();
    _setLinewrap_1.before(_mL_COMMENTRule);
    LinewrapLocator _setLinewrap_2 = c.setLinewrap(1, 1, 1);
    TerminalRule _mL_COMMENTRule_1 = this._somSLMarkedGrammarAccess.getML_COMMENTRule();
    _setLinewrap_2.after(_mL_COMMENTRule_1);
    LinewrapLocator _setLinewrap_3 = c.setLinewrap(1, 1, 1);
    ParserRule _objekttypRule = this._somSLMarkedGrammarAccess.getObjekttypRule();
    _setLinewrap_3.after(_objekttypRule);
    LinewrapLocator _setLinewrap_4 = c.setLinewrap(1, 1, 1);
    ParserRule _beziehungRule = this._somSLMarkedGrammarAccess.getBeziehungRule();
    _setLinewrap_4.before(_beziehungRule);
    LinewrapLocator _setLinewrap_5 = c.setLinewrap(1, 1, 1);
    ParserRule _beziehungRule_1 = this._somSLMarkedGrammarAccess.getBeziehungRule();
    _setLinewrap_5.after(_beziehungRule_1);
    LinewrapLocator _setLinewrap_6 = c.setLinewrap(1, 1, 1);
    ParserRule _is_part_ofRule = this._somSLMarkedGrammarAccess.getIs_part_ofRule();
    _setLinewrap_6.after(_is_part_ofRule);
    LinewrapLocator _setLinewrap_7 = c.setLinewrap(1, 1, 1);
    ParserRule _is_aRule = this._somSLMarkedGrammarAccess.getIs_aRule();
    _setLinewrap_7.after(_is_aRule);
    LinewrapLocator _setLinewrap_8 = c.setLinewrap(1, 1, 1);
    ParserRule _interacts_withRule = this._somSLMarkedGrammarAccess.getInteracts_withRule();
    _setLinewrap_8.after(_interacts_withRule);
    LinewrapLocator _setLinewrap_9 = c.setLinewrap(1, 1, 1);
    ParserRule _anweisungRule = this._somSLMarkedGrammarAccess.getAnweisungRule();
    _setLinewrap_9.after(_anweisungRule);
    LinewrapLocator _setLinewrap_10 = c.setLinewrap(1, 1, 1);
    ParserRule _attributRule = this._somSLMarkedGrammarAccess.getAttributRule();
    _setLinewrap_10.before(_attributRule);
    LinewrapLocator _setLinewrap_11 = c.setLinewrap(1, 1, 1);
    ParserRule _attributRule_1 = this._somSLMarkedGrammarAccess.getAttributRule();
    _setLinewrap_11.after(_attributRule_1);
    LinewrapLocator _setLinewrap_12 = c.setLinewrap(1, 1, 1);
    ParserRule _operatorRule = this._somSLMarkedGrammarAccess.getOperatorRule();
    _setLinewrap_12.before(_operatorRule);
    LinewrapLocator _setLinewrap_13 = c.setLinewrap(1, 1, 1);
    ParserRule _operatorRule_1 = this._somSLMarkedGrammarAccess.getOperatorRule();
    _setLinewrap_13.after(_operatorRule_1);
    LinewrapLocator _setLinewrap_14 = c.setLinewrap(1, 1, 1);
    ParserRule _annotationRule = this._somSLMarkedGrammarAccess.getAnnotationRule();
    _setLinewrap_14.before(_annotationRule);
    LinewrapLocator _setLinewrap_15 = c.setLinewrap(1, 1, 1);
    ParserRule _annotationRule_1 = this._somSLMarkedGrammarAccess.getAnnotationRule();
    _setLinewrap_15.after(_annotationRule_1);
    LinewrapLocator _setLinewrap_16 = c.setLinewrap(1, 1, 1);
    ParserRule _nameRule = this._somSLMarkedGrammarAccess.getNameRule();
    _setLinewrap_16.before(_nameRule);
    LinewrapLocator _setLinewrap_17 = c.setLinewrap(1, 1, 1);
    ParserRule _nameRule_1 = this._somSLMarkedGrammarAccess.getNameRule();
    _setLinewrap_17.after(_nameRule_1);
    LinewrapLocator _setLinewrap_18 = c.setLinewrap(1, 1, 1);
    ParserRule _ignoreRule = this._somSLMarkedGrammarAccess.getIgnoreRule();
    _setLinewrap_18.before(_ignoreRule);
    LinewrapLocator _setLinewrap_19 = c.setLinewrap(1, 1, 1);
    ParserRule _ignoreRule_1 = this._somSLMarkedGrammarAccess.getIgnoreRule();
    _setLinewrap_19.after(_ignoreRule_1);
  }
}
