/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.somsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.uniba.wiai.seda.somsl.ui.internal.SomSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SomSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SomSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SomSLActivator.getInstance().getInjector(SomSLActivator.DE_UNIBA_WIAI_SEDA_SOMSL_SOMSL);
	}
	
}
