/*
* generated by Xtext
*/
package de.uniba.wiai.seda.fha.som.aws;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AwsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.uniba.wiai.seda.fha.som.aws.ui.internal.AwsActivator.getInstance().getInjector("de.uniba.wiai.seda.fha.som.aws.Aws");
	}
	
}
