/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.somslmarked;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SomSLMarkedRuntimeModule extends de.uniba.wiai.seda.somslmarked.AbstractSomSLMarkedRuntimeModule {

}
