/*
 * generated by Xtext
 */
package de.uniba.wiai.seda.somsl.annotation.ui.contentassist

import de.uniba.wiai.seda.somsl.annotation.ui.contentassist.AbstractAnnotationProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AnnotationProposalProvider extends AbstractAnnotationProposalProvider {
}
