/**
 * generated by Xtext
 */
package de.uniba.wiai.seda.somsl.ui.contentassist;

import de.uniba.wiai.seda.somsl.ui.contentassist.AbstractSomSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SomSLProposalProvider extends AbstractSomSLProposalProvider {
}
